server:
  port: 8088
spring:
  application:
    name: springboot-jpa
  datasource:
    url: jdbc:mysql://cdb-8tvjaaoc.cd.tencentcdb.com:10095/jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ltp@zpym
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
polyv:
  appId: foucrmoiej
  userId: 32585cb2a6
  appSecret: 7335ec173f144463bd199f23a463deb0
  url: https://api.polyv.net/live/v3